pipeline {
    agent any
    parameters {
        string(name: 'CLUSTER_NAME', defaultValue: 'mis', description: '')
    }
    stages {
        stage('creds') {
            steps {
                withCredentials(bindings: [usernamePassword(credentialsId: 'api_key_jenkins_update', \
                                                             usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                }
            }
        }
        stage('test') {
            steps {
                sh "echo \"Hello World\""
                sh 'echo $USERNAME'
                sh 'echo $PASSWORD'
            }
        }
        stage('test1') {
            steps {
                sh 'echo $CLUSTER_NAME'
            }
        }
    }
    post {
        always {
            echo 'This will always run'
        }
        success {
            echo 'This will run only if successful'
        }
        failure {
            echo 'This will run only if failed'
        }
        unstable {
            echo 'This will run only if the run was marked as unstable'
        }
        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, if the Pipeline was previously failing but is now successful'
        }
    }
}
